name: dartemis
description: Entity System Framework based on Artemis
version: 0.2.6-dev
author: Dennis Kaselow <Dennis.Kaselow+dartemis@gmail.com>
homepage: https://github.com/denniskaselow/dartemis
dependencies:
  unittest: any